language: php
php:
- 5.6
- 7.0
sudo: false
services:
- mysql
cache:
  directories:
  - node_modules
before_script:
- mkdir -p storage/framework/{cache,views,sessions}
- touch database/database.sqlite
- cp .env.production .env
- php artisan key:generate
- php artisan cache:clear
- php artisan config:clear
- php artisan view:clear
- php artisan clear-compiled
install:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --no-suggest
script:
- php artisan migrate --force --seed
- vendor/bin/phpunit
before_install:
- openssl aes-256-cbc -K $encrypted_cf40e271f765_key -iv $encrypted_cf40e271f765_iv -in travis.enc -out /tmp/travis -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/travis
- ssh-add /tmp/travis
deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r -e "ssh -p 2222 -o 'StrictHostKeyChecking no'" --delete-after $TRAVIS_BUILD_DIR/. vu3015@ares.wrongware.cz:root/subdomains/receipts
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: php artisan migrate --force --seed
    on:
      branch: master
