language: php
php:
- 5.6
- 7.0
sudo: false
services:
- mysql
cache:
  directories:
  - node_modules
before_script:
- mkdir -p storage/framework/{cache,views,sessions}
- touch database/database.sqlite
- cp .env.production .env
- php artisan key:generate
- php artisan cache:clear
- php artisan config:clear
- php artisan view:clear
- php artisan clear-compiled
install:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --no-suggest
script:
- php artisan migrate --force --seed
- vendor/bin/phpunit
- ./vendor/bin/phing/phing/bin/phing
before_install:
- openssl aes-256-cbc -K $encrypted_cf40e271f765_key -iv $encrypted_cf40e271f765_iv
  -in travis.enc -out travis -d && chmod 600 travis
